# ?????
server:
  port: 8090 # ??????? 8090???? MySQL ? 3306 ???????

# Spring ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??? ???????????? URL??? wms_db ????? ???
    # ???? allowPublicKeyRetrieval=true????????????
    url: jdbc:mysql://localhost:3306/wms_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456 # <--- ??????? MySQL ????????? 123456?

# MyBatis-Plus ??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??????? SQL?????
    map-underscore-to-camel-case: true # ????????
